"""create parsing keyword table

Revision ID: c3d2e03b36cf
Revises:
Create Date: 2026-04-28 13:40:33.033993

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c3d2e03b36cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'parsing_keyword',
        sa.Column('decoding', sa.String(), nullable=False),
        sa.Column('keyword', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_parsing_keyword_id'), 'parsing_keyword', ['id'], unique=False
    )
    op.drop_index(op.f('ix_tasks_deadline'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_index(
        op.f('ix_tasks_deadline'), 'tasks', ['deadline'], unique=False
    )
    op.drop_index(op.f('ix_parsing_keyword_id'), table_name='parsing_keyword')
    op.drop_table('parsing_keyword')
    # ### end Alembic commands ###
