services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: service_kgf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ramil1911
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6378:6379"