[project]
name = "fastapikgf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiopath>=0.7.7",
    "aiosmtplib>=5.1.0",
    "aiosqlite>=0.22.1",
    "alembic>=1.18.4",
    "bcrypt>=5.0.0",
    "beautifulsoup4>=4.14.3",
    "dateparser>=1.4.0",
    "defusedxml>=0.7.1",
    "fastapi[standard]>=0.128.0",
    "pyjwt[crypto]>=2.11.0",
    "redis>=7.1.1",
    "requests>=2.32.5",
    "secure-smtplib>=0.1.1",
    "selenium>=4.43.0",
    "sqladmin[full]>=0.23.0",
    "sqlalchemy[asyncio]>=2.0.46",
    "taskiq>=0.12.4",
    "taskiq-aio-pika>=0.6.0",
    "types-defusedxml>=0.7.0.20250822",
    "types-requests>=2.32.4.20260107",
    "wtforms>=3.1.2",
    "zendriver>=0.15.3",
]

[dependency-groups]
dev = [
    "black>=26.1.0",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "ruff>=0.14.13",
]


[tool.mypy]
strict = true


[[tool.mypy.overrides]]
module = "aiopath.*"
ignore_missing_imports = true


[tool.black]
line-length = 79
skip-string-normalization = true
